name: 📄 Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout del código
      - uses: actions/checkout@v3

      # 2) (Opcional) Ver qué hay en la carpeta static/
      - name: Debug: List static files
        run: |
          echo "Contenido de ."
          ls -R static

      # 3) Subir los archivos estáticos como artefacto de Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Cambia "static" por "." para la raíz, o "docs" si usas docs/
          path: .
          artifact_name: github-pages

      # 4) Desplegar a Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact: github-pages
