name: 📄 Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) (Opcional) Verifica que index.html esté en la raíz
      - name: Debug: List root files
        run: |
          echo "Contenido de la raíz del repositorio:"
          ls -R .

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .                 # apunta al directorio con index.html
          artifact_name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact: github-pages
