name: 📄 Deploy to GitHub Pages

# ① Permisos para que la acción pueda publicar en Pages
permissions:
  contents: read    # lectura del repo
  pages: write      # escritura en GitHub Pages
  id-token: write   # para emitir el OIDC token

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages   # ② Vincula al entorno de Pages

    steps:
      # 1) Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) (Opcional) Verifica que tus archivos estén donde los esperas
      - name: Debug: List root files
        run: |
          echo "Contenido de la raíz del repositorio:"
          ls -R .

      # 3) Sube todo lo de la raíz como artefacto de Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .                 # apunta a la carpeta que contiene index.html
          artifact_name: github-pages

      # 4) Despliega a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact: github-pages
