name: 📄 Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Build your site into ./public (adjust for your framework)
      - name: Build static site
        run: |
          npm install
          npm run build  # or hugo, jekyll build, etc.
        # Make sure your build outputs into `public/` (or change below)

      # 3) Upload the built files as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Path to your generated site folder
          path: public
          # This name must match what deploy-pages is looking for:
          artifact_name: github-pages

      # 4) Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # If you want to deploy a different branch or folder, adjust here
          artifact: github-pages
